### ISSUE TITLE
Need to convert to .ort format

### ISSUE THREAD

**Issue by skottmckay** [shubham0204/Scikit_Learn_Android_Demo#1]
FYI: It’s not necessary to convert to .ort format when using the ‘full’ ONNX Runtime package onnxruntime-android - you can use the onnx model. 

The conversion to .ort format is only necessary if using the smaller ‘mobile’ package onnxruntime-mobile, which has limited operators/types (based on popular dnn models used in mobile scenarios) to provide a smaller binary size. That package however does not include traditional ML operators that SciKit-Learn tends to use, so most likely it wouldn't be able to run a model that was converted from SKL.

**Comment by shubham0204** [comment]
Thanks for the information @skottmckay! Does ONNX Runtime model provide any additional optimization over the vanilla ONNX model?

**Comment by skottmckay** [comment]
Its main benefit is allowing usage of the smaller build (onnxruntime-mobile android package) if binary size is a big concern. Same graph optimizations are done by ONNX Runtime for either model format - they're just done ahead of time when creating the .ort format model so we don't have to include optimizer code in the smaller build.

However, there's a chance your model might not be supported by the onnxruntime-mobile package due to the operators/types it uses, so using a .onnx model with onnxruntime-android is the simplest and safest option. 

If binary size is an issue and your model is not supported by onnxruntime-mobile, you can do a custom build to create a package that only includes the operators and types your model requires. This provides the smallest possible binary size.

**Comment by shubham0204** [comment]
@skottmckay The [blog](https://towardsdatascience.com/deploying-scikit-learn-models-in-android-apps-with-onnx-b3adabe16bab) and [Colab notebook](https://github.com/shubham0204/Google_Colab_Notebooks/blob/main/Sklearn_to_ONNX_Conversion.ipynb) have been updated with the information you've provided on ONNX Runtime. Thanks for improving the project!
